<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{

    public function details(){
        return $this->hasMany('App\ArticleTrans' ,'article_id');
    }

    public function translated(){
        return $this->details()->where('lang' ,app()->getLocale())->first();
    }

    public function english(){
        return $this->details()->where('lang' ,'en')->first();
    }

    public function arabic(){
        return $this->details()->where('lang' ,'ar')->first();
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }


    public function delete()
    {
        @unlink(storage_path('uploads/articles')."/{$this->image}");
        @unlink(storage_path('uploads/articles')."/{$this->inner_image}");

        $this->details()->delete();


        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
