<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Candidate extends Model
{
    //
    public function delete()
    {
        @unlink(storage_path('uploads/careers/')."{$this->cv}");
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
