<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Certificate extends Model
{
    //
    public function details(){
        return $this->hasMany('App\CertificateTrans' ,'certificate_id');
    }

    public function translated(){
        return $this->details()->where('lang' ,app()->getLocale())->first();
    }

    public function english(){
        return $this->details()->where('lang' ,'en')->first();
    }

    public function arabic(){
        return $this->details()->where('lang' ,'ar')->first();
    }

    public function delete()
    {
        @unlink(storage_path('uploads/certificates')."/{$this->image}");

        $this->details()->delete();

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
