<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
    public function details(){
        return $this->hasMany('App\ProjectTrans' ,'project_id');
    }

    public function translated(){
        return $this->details()->where('lang' ,app()->getLocale())->first();
    }

    public function english(){
        return $this->details()->where('lang' ,'en')->first();
    }

    public function arabic(){
        return $this->details()->where('lang' ,'ar')->first();
    }

    public function images()
    {
        return $this->hasMany('App\ProjectImage'  ,'project_id');
    }

    public function filter()
    {
        return $this->belongsTo('App\WorkFilter' ,'filter_id')->withDefault();
    }

    public function service()
    {
        return $this->belongsTo('App\Service' ,'service_id')->withDefault();
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }


    public function delete()
    {
        @unlink(storage_path('uploads/projects')."/{$this->image}");

        foreach ($this->images() as $image) {
            @unlink(storage_path('uploads/projects')."/{$image->image}");

            $image->delete();
        }

        $this->details()->delete();

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
