<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    //
    public function details(){
        return $this->hasMany('App\ServiceTrans' ,'service_id');
    }

    public function translated(){
        return $this->details()->where('lang' ,app()->getLocale())->first();
    }

    public function english(){
        return $this->details()->where('lang' ,'en')->first();
    }

    public function arabic(){
        return $this->details()->where('lang' ,'ar')->first();
    }

    public function images()
    {
        return $this->hasMany('App\ServiceImage'  ,'service_id');
    }

    public function main_service()
    {
        return $this->belongsTo('App\Service' ,'parent_id');
    }

    public function sub_services()
    {
        return $this->hasMany('App\Service' , 'parent_id');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function videos()
    {
        return $this->hasMany('App\Video' ,'service_id');
    }

    public function delete()
    {
        @unlink(storage_path('uploads/services')."/{$this->image}");
        @unlink(storage_path('uploads/services')."/{$this->inner_image}");

        foreach ($this->images() as $image) {
            @unlink(storage_path('uploads/services')."/{$image->image}");

            $image->delete();
        }

        $this->details()->delete();

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
