<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    public function delete()
    {
        @unlink(storage_path('uploads/sliders/').$this->image);

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
