<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WorkFilter extends Model
{
    //
    public function details(){
        return $this->hasMany('App\WorkFilterTrans' ,'filter_id');
    }

    public function translated(){
        return $this->details()->where('lang' ,app()->getLocale())->first();
    }

    public function english(){
        return $this->details()->where('lang' ,'en')->first();
    }

    public function arabic(){
        return $this->details()->where('lang' ,'ar')->first();
    }

    public function projects()
    {
        return $this->hasMany('App\Project' , 'filter_id');
    }

    public function delete()
    {
        $this->details()->delete();
        foreach ($this->subs() as $sub) {
            $sub->details()->delete();
            $sub->delete();
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function subs()
    {
        return $this->hasMany('App\WorkFilter' ,'parent_id');
    }

    public function parentFilter()
    {
        return $this->belongsTo('App\WorkFilter' , 'parent_id');
    }
}
